# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd782f733a0c69ff60d31ba81058b705d4fc66f4bb37022f6d22238c2f3a7d1a867dec2f83b4cfbde47aa89c19b0c68fafeb3687c0b5ade5600a141336b8eb89

test:
  secret_key_base: 63e077f2e7b6620ba95b66e14415c52d7d65c8210c50cfb7ab5fd80a77422bf9ebf66f17127e6a64e6788a2bd3aaf3c163e3882222bd08e44f84b7d0d804288c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
